### ISSUE TITLE
Verknüpfung von 4 Counting Kameras

### ISSUE THREAD

**Issue by event-cam** [ubittner/SymconHikvision#1]
Hallo,
wir habe folgende Thematik. Es muss ein System errichtet werden, das an einem Eingang auf 7m Breite zwei Kameras hat und die Werte als eine Enter Value wiedergibt. Auf der Gegenseite ist der Ausgang, ebenfalls mit zwei Kameras, die die Leave Value im gesamten Anzeigt.
Es muss möglich sein, eine Echtzeit Übersicht zu haben wieviele Personen sich im Raum befinden und einen vor-Alarm bei einer gewissen schwelle, wie es schon hier im Projekt super dargestellt ist, einzustellen.

Kameras: HIKVISION iDS-2CD6810F/C
Firmware der Kameras: 5.4.80

**Comment by ubittner** [comment]
Hallo,

für individuelle Projektierungsanfragen wenden Sie sich bitte an normen.thiel(at)firmennet.de

**Comment by ubittner** [comment]
closed
